server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: CloudEagle Assignment

logging:
  level:
    org:
      apache:
        http=DEBUG:
    httpclient:
      wire=DEBUG: